// generated by stringer -type=LogLevel; DO NOT EDIT

package log

import "fmt"

const _LogLevel_name = "UndefinedTraceDebugInfoWarnError"

var _LogLevel_index = [...]uint8{0, 9, 14, 19, 23, 27, 32}

func (i LogLevel) String() string {
	if i < 0 || i+1 >= LogLevel(len(_LogLevel_index)) {
		return fmt.Sprintf("LogLevel(%d)", i)
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
